[package]
name = "rpaper"
version = "0.1.0"
edition = "2021"

[dependencies]
color_space = "0.5.4"
image = "0.25.2"
kmeans_colors = "0.6.0"
palette = "0.7.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
