[package]
name="common"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[lints]
workspace = true

[dependencies]
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"
