pub struct Args {
    rpaper_temp_path: Option<String>,
    rpaper_vars_path: Option<String>,
    rpaper_cache_dir: Option<String>,
    rpaper_scheme_file: Option<String>,
    rpaper_wall_command: Option<String>,
    rpaper_resize_backend: Option<String>,
    rpaper_cache_color_scheme: Option<bool>,
    rpaper_apply_templates: Option<bool>,
    rpaper_cache_wallpaper: Option<bool>,
    rpaper_set_wallpaper: Option<bool>,

    image_processing_change_contrast: Option<bool>,
    image_processing_change_brigtness: Option<bool>,
    image_processing_change_hue: Option<bool>,
    image_processing_change_blur: Option<bool>,
    image_processing_invert: Option<bool>,
    image_processing_h_flip: Option<bool>,
    image_processing_v_flip: Option<bool>,
    image_processing_contrast: Option<f32>,
    image_processing_brigtness: Option<f32>,
    image_processing_hue: Option<u32>,
    image_processing_blur: Option<f32>,

    rwal_cache_dir: Option<bool>,
    rwal_thumb_w: Option<u32>,
    rwal_thumb_h: Option<u32>,
    rwal_accent: Option<u32>,
    rwal_clamp_min: Option<u32>,
    rwal_clamp_max: Option<u32>,

    displays: Option<String>,
    templates: Option<String>,
    variables: Option<String>,
}